server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  cloud:
    gateway:
      routes:
        - id: consumer-route
          uri: lb://consumer-service
          order: 0
          predicates:
            - Path=/api/consumer_service/**
          filters:
            - StripPrefix=2